language: julia
os:
    - linux
    - osx
julia:
    - 0.4
    - nightly
notifications:
    email: false
script:
    - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
    - julia -e 'Pkg.clone(pwd()); Pkg.add("RequestsCache"); Pkg.checkout("RequestsCache")'
    - julia -e 'Pkg.test("RequestsCache",coverage=true)'
after_success:
    - if [ $TRAVIS_JULIA_VERSION = "nightly" ]; then julia -e 'cd(Pkg.dir("RequestsCache")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'; fi
